using System;
using System.Text;

namespace TestVPN.Utils
{
    class Base64Encoder
    {
        public static string Encode(string input)
        {
            return ToBase64(Encoding.UTF8.GetBytes(input));
        }

        public static string Encode(byte[] input)
        {
            return ToBase64(input);
        }

        private static string ToBase64(byte[] input)
        {
            //replace unsupported symbol generated by hash algorithm and remove '-' padding
            return Convert.ToBase64String(input).TrimEnd(Padding).Replace('+', '-').Replace('/', '_'); ;
        }

        private static readonly char[] Padding = { '=' };
    }
}
